### ISSUE TITLE
应该是一个笔误

### ISSUE THREAD

**Issue by w-silence-w** [hookmaster/frida-all-in-one#1]
在https://github.com/hookmaster/frida-all-in-one/blob/master/03.%E5%9F%BA%E6%9C%AC%E6%A1%88%E4%BE%8B%E4%B8%8A%E6%89%8B/%E4%B8%80%E7%AF%87%E6%96%87%E7%AB%A0%E5%B8%A6%E4%BD%A0%E9%A2%86%E6%82%9FFrida%E7%9A%84%E7%B2%BE%E9%AB%93(%E5%9F%BA%E4%BA%8E%E5%AE%89%E5%8D%938.1)/READMD.md
的 《Friday 为什么这么火？》中 “也可以使用gbd、lldb等调试器连上去看”，这里的gbd是gdb吧？

**Comment by r0ysue** [comment]
改好了
